json.id user.id
json.name user.name
json.email user.email
json.password user.password
json.password_confirmation user.password_confirmation
json.age user.age
json.gender user.gender
json.summary user.summary
json.location user.location